/**
 * Migration: Add Profile.openaiEmbedding (+ updatedAt) for the candidate-side
 * jobs page semantic ranker.
 *
 * Background: ExternalJob.embedding is generated by OpenAI text-embedding-3-small.
 * Profile.embedding is generated by Voyage AI — different vector space, can't
 * be compared directly. Before this migration, the jobs route worked around
 * that by regenerating the OpenAI embedding for the profile on EVERY request
 * (cached 15 min in-memory). Persisting it removes that per-request cost.
 *
 * Idempotent — safe to re-run.
 *
 * Run: node scripts/migrations/addProfileOpenAIEmbedding.js
 */

const { sequelize } = require('../../models');

async function up() {
  console.log('🚀 Adding Profile.openaiEmbedding columns\n');

  try {
    // pgvector extension is required (already enabled in this DB; the
    // existing Profile.embedding column wouldn't work otherwise).
    console.log('📦 Step 1: Ensuring pgvector extension is present...');
    await sequelize.query(`CREATE EXTENSION IF NOT EXISTS vector;`);
    console.log('   ✓ vector extension ready');

    console.log('📦 Step 2: Adding "openaiEmbedding" column...');
    await sequelize.query(`
      ALTER TABLE "Profiles"
      ADD COLUMN IF NOT EXISTS "openaiEmbedding" vector(512);
    `);
    console.log('   ✓ openaiEmbedding column added');

    console.log('📦 Step 3: Adding "openaiEmbeddingUpdatedAt" column...');
    await sequelize.query(`
      ALTER TABLE "Profiles"
      ADD COLUMN IF NOT EXISTS "openaiEmbeddingUpdatedAt" TIMESTAMP WITH TIME ZONE;
    `);
    console.log('   ✓ openaiEmbeddingUpdatedAt column added');

    console.log('\n✅ Migration completed successfully\n');
    console.log('Next: profile rows will lazily backfill the embedding on first jobs-page hit,');
    console.log('or on the next profile save. No backfill script needed.');
  } catch (error) {
    console.error('\n❌ Migration failed:', error.message);
    throw error;
  }
}

async function down() {
  console.log('🔙 Reverting Profile.openaiEmbedding columns\n');
  try {
    await sequelize.query(`ALTER TABLE "Profiles" DROP COLUMN IF EXISTS "openaiEmbeddingUpdatedAt";`);
    await sequelize.query(`ALTER TABLE "Profiles" DROP COLUMN IF EXISTS "openaiEmbedding";`);
    console.log('✅ Revert completed\n');
  } catch (error) {
    console.error('\n❌ Revert failed:', error.message);
    throw error;
  }
}

if (require.main === module) {
  const direction = process.argv[2] === 'down' ? down : up;
  direction()
    .then(() => process.exit(0))
    .catch(() => process.exit(1));
}

module.exports = { up, down };
