#!/usr/bin/env node
/**
 * End-to-end Greenhouse Puppeteer adapter smoke test.
 *
 * Boots the Puppeteer adapter against a real Greenhouse apply URL
 * without hitting the database. Useful for validating adapter logic
 * locally before wiring to the submit worker.
 *
 * Usage:
 *   node scripts/testGreenhousePuppeteer.js <greenhouse-apply-url>
 *
 * Options (env):
 *   APPLYPILOT_SUBMIT_FOR_REAL=1   Actually click the submit button.
 *                                  Default off — the script bails just
 *                                  before the submit click so you can
 *                                  eyeball screenshots without spamming
 *                                  the ATS.
 *   APPLYPILOT_TEST_EMAIL          Override the fake email (default:
 *                                  test+applypilot@example.com).
 *   CLOUDINARY_CLOUD_NAME          If set, screenshots upload. If not,
 *                                  the adapter still runs but screenshot
 *                                  URLs in the receipt will be null.
 *
 * What it tests:
 *   ✓ URL parsing / matcher
 *   ✓ DOM-based field harvesting
 *   ✓ mapFields (Claude or deterministic)
 *   ✓ Screenshot capture (upload is optional)
 *   ✗ Does NOT submit unless APPLYPILOT_SUBMIT_FOR_REAL=1
 *
 * Exit code 0 on success, non-zero on any failure.
 */
require('dotenv').config();

const fs = require('fs');
const path = require('path');

async function main() {
  const url = process.argv[2];
  if (!url) {
    console.error('usage: node scripts/testGreenhousePuppeteer.js <greenhouse-apply-url>');
    process.exit(1);
  }

  // Ensure the Puppeteer adapter is the one being picked.
  process.env.APPLYPILOT_ATS_MODE = 'puppeteer';

  const { selectAdapter } = require('../services/ats');
  const adapter = selectAdapter(url);
  if (!adapter) {
    console.error(`✗ No adapter matched ${url}`);
    process.exit(2);
  }
  if (adapter.name !== 'greenhouse-puppeteer') {
    console.error(`✗ Wrong adapter picked: ${adapter.name}. Check APPLYPILOT_ATS_MODE.`);
    process.exit(3);
  }
  console.log(`✓ Matched adapter: ${adapter.name}`);

  // Render a tiny, valid PDF buffer so the file-upload step has something
  // to attach. We use PDFKit (already a dep) to generate a throwaway
  // resume. The harness writes it into the tmpDir via the adapter.
  const PDFDocument = require('pdfkit');
  const resumeBuffer = await new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'LETTER' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.fontSize(18).text('Testing ApplyPilot — please disregard', 50, 60);
    doc.fontSize(11).text('This is a throwaway resume generated by the E2E harness.', 50, 100);
    doc.end();
  });

  const testEmail = process.env.APPLYPILOT_TEST_EMAIL || 'test+applypilot@example.com';

  // The adapter expects the worker's ctx shape. We stub just enough.
  const ctx = {
    app: {
      id: 'e2e-test-app',
      userId: 'e2e-test-user',
      role: 'Senior Android Engineer',
      company: 'Reddit',
      applyUrl: url,
      formAnswers: [
        { question: 'How did you hear about this job?', answer: 'LinkedIn' },
        { question: 'How did you hear about this opportunity?', answer: 'LinkedIn' },
        { question: 'Are you currently authorized to work in the U.S.?', answer: 'Yes' },
        { question: 'Do you require immigration sponsorship?', answer: 'No' },
        { question: 'Privacy policy agreement', answer: 'I agree' },
        { question: 'Current company', answer: 'Acme Corp' },
        { question: 'Zip code', answer: '94105' },
        { question: 'Years of experience', answer: '8' },
      ],
      coverLetter: 'I am excited to apply for this role. This is a test application generated by the ApplyPilot E2E harness — please disregard.',
    },
    applyUrl: url,
    user: { id: 'e2e-test-user', firstName: 'Test', lastName: 'ApplyPilot', email: testEmail },
    profile: {
      phone: '5555555555',
      headline: 'Senior Software Engineer with 8 years of experience',
      summary: 'Do not submit — this is an automated test.',
      linkedinUrl: 'https://linkedin.com/in/test-applypilot',
      location: 'San Francisco, CA',
      zipCode: '94105',
    },
    memory: [],
    demographics: {
      gender: 'Male',
      transgender: 'No',
      sexualOrientation: 'Heterosexual',
      disability: 'No',
      veteran: 'No',
      ethnicity: ['White'],
      workAuthorization: 'Yes',
      sponsorship: 'No',
    },
    resumePdfBuffer: resumeBuffer,
    resumeFileName: 'applypilot-test-resume.pdf',
  };

  // Intercept the adapter's submit so we can bail before actual submit
  // unless the user opted in with APPLYPILOT_SUBMIT_FOR_REAL.
  const realForSubmit = process.env.APPLYPILOT_SUBMIT_FOR_REAL === '1';
  if (!realForSubmit) {
    console.log('ℹ  Dry-run mode. Set APPLYPILOT_SUBMIT_FOR_REAL=1 to actually submit.');
    // Hack: patch Page.prototype.click to no-op when called on a submit
    // selector. Simplest way to unit-test "up to but not including the
    // submit button click" without duplicating the adapter.
    const puppeteer = require('puppeteer');
    const originalLaunch = puppeteer.launch.bind(puppeteer);
    puppeteer.launch = async (opts) => {
      const browser = await originalLaunch(opts);
      const origNewPage = browser.newPage.bind(browser);
      browser.newPage = async () => {
        const page = await origNewPage();

        // Patch page.click (selector-based)
        const origClick = page.click.bind(page);
        page.click = async (selector, ...rest) => {
          if (typeof selector === 'string' && /submit|commit/i.test(selector)) {
            console.log(`ℹ  Dry-run: skipping page.click on ${selector}`);
            return;
          }
          return origClick(selector, ...rest);
        };

        // Patch page.$ so returned ElementHandles also have a gated click.
        const orig$ = page.$.bind(page);
        page.$ = async (selector) => {
          const el = await orig$(selector);
          if (el && typeof selector === 'string' && /submit|commit/i.test(selector)) {
            const origElClick = el.click.bind(el);
            el.click = async (...args) => {
              console.log(`ℹ  Dry-run: skipping el.click on ${selector}`);
              return;
            };
          }
          return el;
        };

        return page;
      };
      return browser;
    };
  }

  try {
    const receipt = await adapter.submit(ctx);
    console.log('✓ Adapter returned receipt:');
    console.log(JSON.stringify(receipt, null, 2));
    if (receipt?.screenshots?.length) {
      console.log(`✓ ${receipt.screenshots.length} screenshot(s) captured.`);
      for (const s of receipt.screenshots) {
        console.log(`   · ${s.label}: ${s.url || '(no url — Cloudinary not configured)'}`);
      }
    }
    process.exit(0);
  } catch (err) {
    if (err.needsHuman) {
      console.log('ℹ  Adapter paused for human input (expected for hardened forms).');
      console.log('   Reason:', err.message);
      if (err.blockers?.length) {
        console.log('   Blockers:');
        for (const b of err.blockers) {
          console.log(`     - ${b.label || b.name}: ${b.reason}`);
        }
      }
      if (err.screenshots?.length) {
        console.log(`   ${err.screenshots.length} screenshot(s) captured before pause.`);
        for (const s of err.screenshots) {
          console.log(`   · ${s.label}: ${s.url || '(no url — Cloudinary not configured)'}`);
        }
      }
      process.exit(0); // expected flow
    }
    console.error('✗ Adapter threw:', err.message);
    if (err.stack) console.error(err.stack);
    if (!realForSubmit && /confirmation page|did not return/i.test(err.message)) {
      console.log('ℹ  Expected in dry-run: submit was skipped so no confirmation page.');
      if (err.screenshots?.length) {
        console.log(`   ${err.screenshots.length} screenshot(s) captured.`);
        for (const s of err.screenshots) {
          console.log(`   · ${s.label}: ${s.url || '(no url — Cloudinary not configured)'}`);
        }
      }
      process.exit(0);
    }
    if (err.screenshots?.length) {
      console.error(`   ${err.screenshots.length} screenshot(s) captured before error.`);
      for (const s of err.screenshots) {
        console.error(`   · ${s.label}: ${s.url || '(no url — Cloudinary not configured)'}`);
      }
    }
    process.exit(4);
  }
}

main().catch((e) => {
  console.error('Fatal:', e);
  process.exit(5);
});
