const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Profile = sequelize.define('Profile', {
  id: {
    type: DataTypes.UUID,
    defaultValue: DataTypes.UUIDV4,
    primaryKey: true
  },
  userId: {
    type: DataTypes.UUID,
    allowNull: false,
    references: {
      model: 'Users',
      key: 'id'
    },
    onDelete: 'CASCADE'
  },
  // Profile Picture
  profilePicture: {
    type: DataTypes.TEXT, // Base64 or URL
    allowNull: true
  },
  coverImage: {
    type: DataTypes.TEXT, // Base64 or URL for cover/banner
    allowNull: true
  },
  // Basic Info
  title: {
    type: DataTypes.STRING,
    allowNull: false
  },
  headline: {
    type: DataTypes.STRING, // Short tagline
    allowNull: true
  },
  location: {
    type: DataTypes.STRING
  },
  phone: {
    type: DataTypes.STRING
  },
  linkedinUrl: {
    type: DataTypes.STRING
  },
  githubUrl: {
    type: DataTypes.STRING
  },
  portfolioUrl: {
    type: DataTypes.STRING
  },
  twitterUrl: {
    type: DataTypes.STRING
  },
  websiteUrl: {
    type: DataTypes.STRING
  },
  summary: {
    type: DataTypes.TEXT
  },
  // Skills with proficiency levels
  skills: {
    type: DataTypes.JSONB,
    defaultValue: {}
  },
  experience: {
    type: DataTypes.JSONB,
    defaultValue: []
  },
  education: {
    type: DataTypes.JSONB,
    defaultValue: []
  },
  // Enhanced Projects with images, links, tech stack
  projects: {
    type: DataTypes.JSONB,
    defaultValue: []
  },
  // Certifications
  certifications: {
    type: DataTypes.JSONB,
    defaultValue: []
  },
  // Languages
  languages: {
    type: DataTypes.JSONB,
    defaultValue: []
  },
  // Availability status
  availabilityStatus: {
    type: DataTypes.STRING,
    defaultValue: 'open' // open, not-looking, actively-looking
  },
  // AI-generated fields
  aiSummary: {
    type: DataTypes.TEXT
  },
  aiStrengths: {
    type: DataTypes.JSONB,
    defaultValue: []
  },
  aiRecruiterInsights: {
    type: DataTypes.TEXT
  },
  aiKeywords: {
    type: DataTypes.JSONB,
    defaultValue: []
  },
  isPublic: {
    type: DataTypes.BOOLEAN,
    defaultValue: true
  },
  // Import tracking fields
  // Original uploaded resume text (raw text extracted from PDF/DOCX)
  originalResumeText: {
    type: DataTypes.TEXT,
    allowNull: true
  },
  importSource: {
    type: DataTypes.ENUM('manual', 'csv', 'linkedin', 'email', 'ats', 'api', 'referral'),
    defaultValue: 'manual',
    allowNull: true
  },
  importedAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  importBatchId: {
    type: DataTypes.UUID,
    allowNull: true
  },
  // RAG: pgvector embedding for semantic search (Voyage AI voyage-3-lite, 512 dims)
  // Used by recruiter-side candidate search.
  embedding: {
    type: DataTypes.VECTOR(512),
    allowNull: true
  },
  embeddingUpdatedAt: {
    type: DataTypes.DATE,
    allowNull: true
  },
  // Second embedding for the candidate-side jobs page. Generated by OpenAI
  // text-embedding-3-small so it lives in the same vector space as
  // ExternalJob.embedding (which is also OpenAI). Pre-computing here lets
  // the jobs page skip the per-request OpenAI call that the in-memory
  // cache used to paper over.
  openaiEmbedding: {
    type: DataTypes.VECTOR(512),
    allowNull: true
  },
  openaiEmbeddingUpdatedAt: {
    type: DataTypes.DATE,
    allowNull: true
  }
}, {
  timestamps: true,
  hooks: {
    afterSave: async (profile, options) => {
      // Auto-generate embeddings when embedding-relevant fields change.
      const embeddingFields = ['title', 'headline', 'summary', 'skills', 'aiKeywords', 'experience'];
      const changed = options.fields || [];
      const relevantChange = changed.some(f => embeddingFields.includes(f));

      // Invalidate the per-user /external-jobs cache (parsed embedding +
      // skill set) so the next jobs request picks up the fresh data
      // instead of serving stale rankings for up to 5 minutes. Safe to
      // call even when no relevant field changed — it's just a Map.delete.
      try {
        const { invalidateProfileForJobsCache } = require('../services/jobEmbeddingService');
        invalidateProfileForJobsCache(profile.userId);
      } catch { /* service unavailable during boot — fine */ }

      // ── Voyage embedding (recruiter-side candidate search) ──
      // Skip if VOYAGE_API_KEY is not configured
      if (process.env.VOYAGE_API_KEY) {
        // Only regenerate if relevant fields changed (or embedding is missing)
        if (relevantChange || !profile.embedding) {
          try {
            // Lazy-load to avoid circular dependency
            const { embeddingService } = require('../services/embeddingService');
            await embeddingService.generateProfileEmbedding(profile);
          } catch (error) {
            // Don't fail the save if embedding generation fails
            console.error(`[Profile Hook] Voyage embedding generation failed for ${profile.id}:`, error.message);
          }
        }
      }

      // ── OpenAI embedding (candidate-side jobs page) ──
      // Skip if OPENAI_API_KEY is not configured
      if (process.env.OPENAI_API_KEY) {
        if (relevantChange || !profile.openaiEmbedding) {
          try {
            const { regenerateProfileOpenAIEmbedding } = require('../services/jobEmbeddingService');
            // Fire-and-forget — don't block the save response on the API call.
            regenerateProfileOpenAIEmbedding(profile).catch(err => {
              console.error(`[Profile Hook] OpenAI embedding generation failed for ${profile.id}:`, err.message);
            });
          } catch (error) {
            console.error(`[Profile Hook] Could not load jobEmbeddingService:`, error.message);
          }
        }
      }
    }
  }
});

module.exports = Profile;
